//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_Learning
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net.Mail;
    using System.Security.Cryptography;
    using System.Text;
    using System.Windows.Forms;

    public partial class Korisnik
    {
        public int id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int uloga_id { get; set; }
        public System.DateTime datumPridruzivanja { get; set; }
        public string privremeniZapis { get; set; }
        public string slikaProfila { get; set; }
        public string opisProfila { get; set; }
    
        public virtual Uloga Uloga { get; set; }


        public static string ShaKriptiranje(string korIme, string lozinka)
        {
            //MessageBox.Show($"Ime: {korIme}\nLozinka: {lozinka}");

            var hash = new SHA1Managed().ComputeHash(Encoding.UTF8.GetBytes(korIme));
            string kriptiranoIme = string.Concat(hash.Select(b => b.ToString("x2")));

            hash = new SHA1Managed().ComputeHash(Encoding.UTF8.GetBytes(kriptiranoIme + lozinka));
            string kriptiran = string.Concat(hash.Select(b => b.ToString("x2")));

           //MessageBox.Show($"Pravi: {kriptiran}");
            return kriptiran;
        }

        public static string GenerirajLozinku()
        {
            Random kutijaSrece = new Random();
            int x;
            string novaLozinka = "";

            for (int i = 0; i < 8; i++)
            {
                do
                {
                    x = kutijaSrece.Next(48, 123);

                } while ((x >= 58 && x <= 64) || (x >= 91 && x <= 96));

                novaLozinka += (char)x;
            }

            return novaLozinka;
        }

        public void PosaljiNaMail( string generiranaLozinka )
        {
            
            try
            {
                MailMessage mail = new MailMessage();
                SmtpClient SmtpServer = new SmtpClient("smtp.gmail.com");

                mail.From = new MailAddress("cselearninginfo@gmail.com");
                mail.To.Add(email);
                mail.Subject = "Novo generirana lozinka za E-learning";
                mail.Body = $"Nedavno ste zatražili promjenu lozinke za E-learning aplikaciju.<br>Vaši novi podaci su: <br><br> <pre style=\"font-family: verdana; font-size: 18px; \">" +
                            $"     Korisničko ime: <b>{username}</b> <br>     Lozinka: <b>{generiranaLozinka}</b> </pre><br><br><br>" +
                            $"Ukoliko niste zatražili promjenu lozinke, ignorirajte ovaj e-mail.<br>" +
                            $"<span style=\"color: red; \">Ova poruka je automatski generirana, nemojte na nju odgovarati!</span>";

                mail.IsBodyHtml = true;

                SmtpServer.Port = 587;
                SmtpServer.Credentials = new System.Net.NetworkCredential("cselearninginfo@gmail.com", "FOQ8cena");
                SmtpServer.EnableSsl = true;

                SmtpServer.Send(mail);
                MessageBox.Show($"Lozinka je uspjesno generirana.\nPodaci su poslani na {email}.");
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
            
        }


    }
}
